### ISSUE TITLE
Comment some features that you would like to add to the program

### ISSUE THREAD

**Issue by EmiyaKazuto** [EmiyaKazuto/CCC101-Group-Project#6]
Comment lng Guys. Kung kaya I-add lng.

**Comment by babila123** [comment]
How about ang formula or ang pagsolve sa combination or permutation, since some of the calculator (scical) meron?hihihi

**Comment by shdwfnd** [comment]
sigii try nako consider ng mga ing ana sa pagdagdah sa mga buttons and all. si shaina actually ang mag code sa atong logic na magsolve2 ana, ako ra ang mag buhat ug buttons hehe shaina u decide

**Comment by Shaina-Uy** [comment]
Hellooo, hmm actually we can add those as long as ma fulfill and basic requirements. Let's see na lang siguro muna? Accomplish muna natin basic reqs then if okay na, decide tayp ulit if mag add tayo other functionalities.
